--- #YAML:1.0
name:                ExtUtils-InstallPAR
version:             0.01
abstract:            Install .par's into any installed perl
license:             perl
author:              
    - Steffen Mueller <smueller@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    PAR::Dist:                     0.40
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
